id: 387af8ea2901481c82404803e44ed89c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_438-Tara_with_Twenty-One_Verses_of_Homage-v2
  language: en
  author: ''
  volume: {}
